### ISSUE TITLE
Incompatibility with 2.3.4?

### ISSUE THREAD

**Issue by Rinkwraith** [anaggh/private-mode#1]
Apologies for not posting more details, but I'm sending this a couple of days after the fact, in the hope that it helps someone.

I installed the Private Mode plugin on Bludit 2.3.4 (standard edition, build: 20180402) and it complained that the constructor for the _Login_ class does not accept zero arguments.

As a quick bodge, I changed _plugin.php_ to

`$login = new Login(null);`

and this seems to have sorted it.

**Comment by anaggh** [comment]
Hi @Rinkwraith . Sorry for the confusion but I think you installed the plugin for Bludit v3 in v2.3.4. Please install this one instead - https://github.com/anaggh/private-mode/releases/tag/v2.3

**Comment by Rinkwraith** [comment]
No worries mate. I probably did exactly that - damn web server gave me so many headaches that by the time I got to installing plugins, I suspect I wasn't paying enough attention. :-)
